### ISSUE TITLE
Neat!

### ISSUE THREAD

**Issue by mweth** [Nikro/MMM-WhisperGPT#1]
Is there an all-incompassing installer for this module or do I need to separately install each dependency?

**Comment by Nikro** [comment]
@mweth - hey, thanks!

Picovoice / Porcupine / LangChain - these are installed via `npm install`.

Whisper / Mimic3 - these are not installed and I personally install these not on the client device but on a server that sits on the network.

Then there's `mpg123` and `aplay` which depend on the OS you're installing (one is used for mp3s and another for wav) - and `lame` as well. 

I just published an article which explains how it all works: https://nikro.me/articles/professional/crafting-our-ai-assistant/
