### ISSUE TITLE
`Error: PVRecorder failed to initialize` when bringing up the MMM-WhisperGPT

### ISSUE THREAD

**Issue by swapanshridhar** [Nikro/MMM-WhisperGPT#3]
# Problem: 

When bringing up MagicMirror2 with the [MMT-WhisperGPT](https://github.com/Nikro/MMM-WhisperGPT) module added, getting the following error:

`Error: PVRecorder failed to initialize`

`Screenshot`:

<img width="1306" alt="Screen Shot 2023-07-21 at 5 37 12 PM" src="https://github.com/Nikro/MMM-WhisperGPT/assets/26994497/183146af-1a2d-44b5-8981-dfcd195439db">

Issue at installed file:

MagicMirror/modules/MMM-WhisperGPT/node_modules/@picovoice/pvrecorder-node/dist/pv_recorder.js:45

```
    /**
     * PvRecorder constructor.
     *
........
     */
    constructor(deviceIndex, frameLength, bufferSizeMSec = 1000, logOverflow = true, logSilence = true) {
        let porcupineHandleAndStatus;
        try {                                                                 V----------- DEVICE INDEX IS SET to 0 when debugged. 
            porcupineHandleAndStatus = PvRecorder._pvRecorder.init(deviceIndex,    
            frameLength, bufferSizeMSec, logOverflow, logSilence);                    
        }
        catch (err) {
            (0, errors_1.default)(err.code, err);
        }
        const status = porcupineHandleAndStatus.status;
....
```

**The issue: As Device Index is set to 0, the device index doesn't seem to exist in the audio device that is connected. In this case the Mic.**

# System Details:

## Hardware: 

 - `Device`: RaspberryPi 4B 8 GB
 - `Mic`: [Logitech for Creators BlueSnowball iCE USB Microphone](https://www.amazon.com/dp/B014PYGTUQ?psc=1&ref=ppx_yo2ov_dt_b_product_details)
 -  `Speaker`: [Anker Soundcore connected via USB](https://www.amazon.com/Anker-Soundcore-Bluetooth-Exclusive-Water-Resistant/dp/B01MTB55WH/ref=sr_1_4?keywords=anker+bluetooth&qid=1689983444&sr=8-4) 

_Mic and Speaker has been tested to be working fine outside the [MMT-WhisperGPT](https://github.com/Nikro/MMM-WhisperGPT) module by using **arecord** command as mentioned in the setup: [How To Set Up Your Own Assistant at Home](https://nikro.me/articles/professional/crafting-our-ai-assistant/)_

## Software:

 - `OS`: Raspbian 64 bit

## Dependencies

- **Mimic3** and **Whisper** is hosted in a different node and confirmed that they are working fine.
   - Also, please note that `pvRecorder` issue reported is happening even before we will hot Mimic3 or Whisper.

**Comment by swapanshridhar** [comment]
For the time being I am able to get pass this issue by hardcoding the value for `deviceIndex` to `-1` as of now, and that works.

## To unblock, one can do the following:

### File: 

`MagicMirror/modules/MMM-WhisperGPT/node_modules/@picovoice/pvrecorder-node/dist/pv_recorder.js`




Once we know that Mic is working fine (arecord commands mentioned in description), one can dabble with changing Device Index.

#### Before:

`porcupineHandleAndStatus = PvRecorder._pvRecorder.init(deviceIndex, frameLength, bufferSizeMSec, logOverflow, logSilence);`

#### Change:

`porcupineHandleAndStatus = PvRecorder._pvRecorder.init(-1, frameLength, bufferSizeMSec, logOverflow, logSilence);`

I got this information by Googling and stumbling upon this link: https://github.com/Picovoice/pvrecorder/issues/27#issuecomment-1074467372



## Proper Fix:

- I believe (haven't tested, as I am dealing with other issues in this module which I am trying to debug) the `deviceIndex = 0`  is coming from this hardcoding:

https://github.com/Nikro/MMM-WhisperGPT/blob/57503ccaf43285bc448e697b20fe8443540ee2cf/MMM-WhisperGPT.js#L25


- But point is how will one figure out what is the device Index ? I believe if we can't automate that (if its cumbersome), we may just put details in **README** on how to figure out the DeviceIndex. 
- In my case, it happened to be `-1` instead of the assumed `0`.  Not sure, if its because my Mic was connected via USB and get a device id = -1. Not an expert and haven't explored it much given I have a hardcoding fix working as of now.

**Comment by Nikro** [comment]
@swapanshridhar - hey, it's awesome to see people using it :)

There's a config setting for that `audioDeviceIndex` - it's in the README.md example, the default values are later extended, so if you want to use your own index (as I predicted, because we all have different devices) - you can just specify it:

```
var config = {
    modules: [
        {
            module: 'MMM-WhisperGPT',
            config: {
                // See below for configurable options
                picovoiceKey: 'xxx',
                picovoiceWord: 'JARVIS',
                picovoiceSilenceTime: 3,
                picovoiceSilenceThreshold: 600,
                audioDeviceIndex: 3, // like here ;)
                openAiKey: 'xxx',
                openAiSystemMsg: 'xxx',
                whisperUrl: '192.168.1.5:9000/asr',
                whisperMethod: 'openai-whisper',
                mimic3Url: '192.168.1.6:59125'
            }
        }
    ]
}
```
